# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_read_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated'], 'permissions': (('view_post', 'Can view posts'),)},
        ),
    ]
